### PR TITLE
fix(colformat_md): follow internal change of flextable data structure

### LINKED ISSUE #100: colformat_md() not working with flextable version 0.9.5
R version 4.3.3, ftExtra version 0.6.2. The example code from the README for parsing markdown texts using colformat_md() runs as expected when flextable version 0.9.4 is installed, but doesn't when flextable version 0.9.5 is installed. The resulting table made with flextable 0.9.5 shows all of the markdown syntax, rather than converting it to formatted text. I've reproduced this on 2 systems.

### PR DESCRIPTION
**Pull request by atusy**
fixes #100

### CODE REVIEW

File: R/colformat.R [hunk 1]
```diff
@@ -51,7 +51,12 @@ colformat_md <- function(x,
   }
 
   dataset <- x[[part]]$dataset
-  content <- x[[part]][["content"]][["content"]][["data"]]
+  content <- if (is.null(x[[part]][["content"]][["content"]])) {
+    # flextable >= 0.9.5
+    x[[part]][["content"]][["data"]]
+  } else {
+    x[[part]][["content"]][["content"]][["data"]]
+  }
```
Comment (atusy) [inline R/colformat.R:59]: @davidgohel The issue #100 seems to be happened because of the change in the internal data structure. Am I right? (I have not yet reviewed the git log)

**Comment by atusy** [comment]
I will drop support for flextable < 0.9.5 by specifying required version in `DESCRIPTION`

File: R/colformat.R (hunk 1 above)
Comment (davidgohel) [reply R/colformat.R]: Yes the internal data structure has been simplified. Sorry I ran revdepcheck and did not catch that issue

**Comment by davidgohel** [comment]
@atusy is it possible to use exported functions (I. E. as_paragraph or append_chunk) instead of usung internal structures?

**Comment by atusy** [comment]
@davidgohel

Thanks. I understand robust code should avoid relying on the internal data structure.
However, I find no exported functions suits my use cases...

1. To convert texts in selected columns, I need access to the internal data to retrieve target markdown texts...
2. `colformat_md`'s `j` argument supports the tidy-selection. This also requires access to the internal data structure... I like the experience of the tidy-selection, but I regret the inconsistency with the other colformat functions in the original **flextable** package.

To solve both, I need **flextable** to export a function that provides access to the internal data structure. However, but I do not think this is a good idea because **flextable** may face a difficulty to change the internal data structure in the future.

To solve the first one, I have a suggestion. `flextable::compose()`'s `value` argument can be enhanced to accept a callback that receives a paragraph selected by `x`, `i`, and `j` arguments, and returns the modified paragraph.

Anyway, I would be happy to know if there is a way for **ftExtra** to avoid the dependency on the internal data.
Thanks again.

**Comment by davidgohel** [comment]
Thanks for the suggestion 😊
I don't have a computer right now to try your suggestion but I will have a try later this week and iterate on the subject in this thread

**Comment by atusy** [comment]
My pleasure!

I would like to release a fix as soon as possible, so let me continue relying on the internal data structure for now.

Maybe I can do better in the near future :smile:
